### ISSUE TITLE
[Crowdfunding]

### ISSUE THREAD

**Issue by LifeIsStrange** [tohojo/bufferbloat-net#16]
I believe that you should make a kickstarter/similar website campaign for being able to create an even faster wifi,and to remunerate you because you have merit!
thank you for making a better world.
<3

**Comment by dtaht** [comment]
We have both patreon and gofundme. We get 180 dollars a month for the work of a half dozen people. It's been too depressing to think about. it barely pays for 1/3 of the server time we use up.

**Comment by LifeIsStrange** [comment]
Well humans are dumb and egoist :/
I just want you to know that you are modern heroes
