### ISSUE TITLE
Unable to view RRUL graphs on site

### ISSUE THREAD

**Issue by jawz101** [tohojo/bufferbloat-net#34]
https://www.bufferbloat.net/projects/codel/wiki/RRUL_Rogues_Gallery/

and

https://www.bufferbloat.net/projects/bloat/wiki/RRUL_Chart_Explanation/

**Comment by tohojo** [comment]
"." <notifications@github.com> writes:

> https://www.bufferbloat.net/projects/codel/wiki/RRUL_Rogues_Gallery/

Yeah, the machine hosting the webserver is experiencing problems. Should
hopefully be fixed sometime in the next few days...

**Comment by tohojo** [comment]
Should be back online now :)

**Comment by jawz101** [comment]
Thanks.  Looks good
