### ISSUE TITLE
Some things that are unclear from the 'Getting SQM Running Right' article

### ISSUE THREAD

**Issue by woutervisee** [tohojo/bufferbloat-net#43]
I just arrived at the bufferbloat website, I've read a few introductory articles, now I'm reading 'what can I do about bufferbloat', and in Step 1 the author directs me to the 'getting sqm running right' to see an example of SQM tuning.

This article is very informative but I feel like I'm going off the deep end here. For example the first plot, is that before or after the tuning? From the text it's not clear to me.

And then the article is about SQM tuning, but it looks to me like they're tuning the router's bandwith caps to avoid filling a buffer at the ISP side and not the queue management. Is that right? It's not in the text as far as I can see, maybe I missed something.

**Comment by tohojo** [comment]
Wouter Visee <notifications@github.com> writes:

> I just arrived at the bufferbloat website, I've read a few
> introductory articles, now I'm reading 'what can I do about
> bufferbloat', and in Step 1 the author directs me to the 'getting sqm
> running right' to see an example of SQM tuning.
>
> This article is very informative but I feel like I'm going off the
> deep end here. For example the first plot, is that before or after the
> tuning? From the text it's not clear to me.
>
> And then the article is about SQM tuning, but it looks to me like
> they're tuning the router's bandwith caps to avoid filling a buffer at
> the ISP side and not the queue management. Is that right? It's not in
> the text as far as I can see, maybe I missed something.

Hmm, yeah, I can see how there's a "step 0" missing here: the objective
is to get the queue under control, which is usually done by rate
limiting. The queue management itself doesn't need much tuning, so the
tuning consists in finding the right rate to limit at which will
successfully move the queue to where you can control it, without wasting
too much bandwidth...
