### ISSUE TITLE
The tips in the "Windows Tips" section don't work

### ISSUE THREAD

**Issue by ktmriki** [tohojo/bufferbloat-net#45]
The command "set-nettcpsetting -CongestionProvider CTCP" that is suggested on the page returns a Read-only error in and elevated PowerShell. It doesn't work in the current version of Win10.

**Comment by tohojo** [comment]
ktmriki <notifications@github.com> writes:

> The command "set-nettcpsetting -CongestionProvider CTCP" that is
> suggested on the page returns a Read-only error in and elevated
> PowerShell. It doesn't work in the current version of Win10.

Huh, right. Do you happen to know if there's an alternative for win10,
or should we maybe just remove that bit entirely?

-Toke
