### ISSUE TITLE
Unable to connect to SSL on subdomain snapon.lab.bufferbloat.net

### ISSUE THREAD

**Issue by MaartenW** [tohojo/bufferbloat-net#46]
Images don't load on https://www.bufferbloat.net/projects/codel/wiki/RRUL_Rogues_Gallery/

**Comment by tohojo** [comment]
Maarten Wolzak <notifications@github.com> writes:

> Images don't load on
> https://www.bufferbloat.net/projects/codel/wiki/RRUL_Rogues_Gallery/

Ah, right; I definitely have those images lying around somewhere, will
see if I can't get them fixed. Thanks for the report! :)

-Toke

**Comment by richb-hanover** [comment]
The Wayback Machine is your friend...

A recent page holds most of the images: https://web.archive.org/web/20190215023433/https://www.bufferbloat.net/projects/codel/wiki/RRUL_Rogues_Gallery

An early posting also shows the TCP Global Synchronization image at: https://web.archive.org/web/20141203012210/http://www.bufferbloat.net/projects/codel/wiki/RRUL_Rogues_Gallery

**Comment by tohojo** [comment]
Rich Brown <notifications@github.com> writes:

> The Wayback Machine is your friend...
>
> A recent page holds most of the images: https://web.archive.org/web/20190215023433/https://www.bufferbloat.net/projects/codel/wiki/RRUL_Rogues_Gallery
>
> An early posting also shows the TCP Global Synchronization image at: https://web.archive.org/web/20141203012210/http://www.bufferbloat.net/projects/codel/wiki/RRUL_Rogues_Gallery

Ah, great, didn't go that far back; thanks! The live page should work
again now :)
