### ISSUE TITLE
Not always the router

### ISSUE THREAD

**Issue by es20490446e** [tohojo/bufferbloat-net#47]
bufferbloar.net usually points the router as the source of buffer-bloat, but that's not always the case. It can be any network device.

For example my computer suffered from it on the Ethernet cable, but when I tried with a second computer the phenomenon didn't appear. So the Ethernet adapter was the cause itself, not the router.

I think it would be good clarifying that it could be due to any device. And mention that usually the router is to blame, just not always.

**Comment by tohojo** [comment]
Alberto Salvia Novella <notifications@github.com> writes:

> bufferbloar.net usually points the router as the source of buffer-bloat, but that's not always the case. It can be any network device.
>
> For example my computer suffered from it on the Ethernet cable, but when I tried with a second computer the phenomenon didn't appear. So the Ethernet adapter was the cause itself, not the router.
>
> I think it would be good clarifying that it could be due to any device. And mention that usually the router is to blame, just not always.

Which page are you referring to here, specifically?

**Comment by es20490446e** [comment]
All the documentation presumes that the fix lies withing the router.

For example, [this](https://www.bufferbloat.net/projects/bloat/wiki/What_can_I_do_about_Bufferbloat/).

**Comment by es20490446e** [comment]
Thanks 👍
