### ISSUE TITLE
Hundreds of errors when running hugo locally

### ISSUE THREAD

**Issue by richb-hanover** [tohojo/bufferbloat-net#5]
When I use `hugo serve` on the master branch, I get hundreds of these errors:

````
ERROR: 2016/06/14 error processing shortcode shortcodes/issue_journal.html
 ERR: template: shortcodes/issue_journal.html:5:14: executing "shortcodes/issue_journal.html" at <markdownify>: wrong type for value; expected string; got template.HTML
````
I don't know enough about hugo to know how to fix them. Thoughts? Thanks!

**Comment by tohojo** [comment]
Hmm, what version of Hugo are you running?

**Comment by richb-hanover** [comment]
I had been running 0.15, but OSX brew now supports 0.16. No more errors!

**Comment by tohojo** [comment]
Awesome!
