### ISSUE TITLE
How to trigger a re-render of hugo site?

### ISSUE THREAD

**Issue by richb-hanover** [tohojo/bufferbloat-net#51]
I updated the bufferbloat.net repo to scratch a couple itches...

* Fix the "What Can I Do About Bufferbloat?" page to be more explicit and less duplicative of other pages.
* Remove/Update references to LEDE in favor of "OpenWrt"
* Make a pass through the CeroWrt index.md page to note that it's an archive of older work
* Fix a couple broken links

How does the official bufferbloat.net site get updated with the new content? Thanks.

**Comment by tohojo** [comment]
Rich Brown <notifications@github.com> writes:

> I updated the bufferbloat.net site to scratch a couple itches...
>
> * Fix the "What Can I Do About Bufferbloat?" page to be more explicit and less duplicative of other pages.
> * Remove/Update references to LEDE in favor of "OpenWrt"
> * Fix a couple broken links
>
> How does the official bufferbloat.net site get updated with the new
> content? Thanks.

Automatically, in theory - let me check the web-hook :)

**Comment by tohojo** [comment]
Toke Høiland-Jørgensen <toke@toke.dk> writes:

> Rich Brown <notifications@github.com> writes:
>
>> I updated the bufferbloat.net site to scratch a couple itches...
>>
>> * Fix the "What Can I Do About Bufferbloat?" page to be more explicit and less duplicative of other pages.
>> * Remove/Update references to LEDE in favor of "OpenWrt"
>> * Fix a couple broken links
>>
>> How does the official bufferbloat.net site get updated with the new
>> content? Thanks.
>
> Automatically, in theory - let me check the web-hook :)

Right, there was a permission error on the build server - should be
fixed now...

**Comment by richb-hanover** [comment]
Thanks!
